### ISSUE TITLE
Same install; one works the other doesn't

### ISSUE THREAD

**Issue by steveyum** [drewblessing/gitlab-cli#49]
have it working fine on one ubuntu 14.04 server. the other throws an error:

Unable to get users
undefined method `response' for #<Errno::ECONNREFUSED: Connection refused - connect(2)>

this is driving me nuts. there doesn't seem to be any difference between the two servers. please advise
